apiVersion: v1
kind: ConfigMap
metadata:
  name: devsu-devops-python-config
  namespace: prod-devsu-demo
data:
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "*"

  DB_ENGINE: "mysql"
  DB_NAME: "devsu_demo"
  DB_PORT: "3306"