apiVersion: v1
kind: Service
metadata:
  name: devsu-devops-python
  namespace: devsu-demo
spec:
  selector:
    app: devsu-devops-python
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: LoadBalancer