apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-devsu-demo

resources:
  - ../../base
  - namespace.yaml
  - configmap.yaml

images:
  - name: ghcr.io/pepereyra/devsu-devops-python
    newTag: c7b2b93c83e76216abb2c9e72a548042e83c3ffd

replicas:
  - name: devsu-devops-python
    count: 2