apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-devsu-demo

resources:
  - ../../base
  - namespace.yaml
  - configmap.yaml

images:
  - name: ghcr.io/pepereyra/devsu-devops-python
    newTag: 7e1b83da164c053ebd4c1551bc87ca9cd373b3f2

replicas:
  - name: devsu-devops-python
    count: 2