apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devsu-demo

resources:
  - ../../base

images:
  - name: ghcr.io/pepereyra/devsu-devops-python
    newTag: latest

replicas:
  - name: devsu-devops-python
    count: 2