name: Config Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  trivy-config-scan:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy config scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: .
          format: table
          exit-code: "0"
          severity: HIGH,CRITICAL